rate_limiter:
  default_interaval: 10
  default_capacity: 10

service:
  host: localhost
  port: 8080

backends:
  - host: localhost
    scheme: http
    port: 8081
  - host: localhost
    scheme: http
    port: 8082
  - host: localhost
    scheme: http
    port: 8083
  - host: localhost
    scheme: http
    port: 8084

load_balancer:
  time_check: 10
  endpoint_health_check: /check

db:
  host: "localhost"
  port: 5432
  user: user
  password: password
  db_name: loadbalancer

logger:
  level: debug